import 'package:equatable/equatable.dart';

class MaterialType extends Equatable {
  final int id;
  final String name;
  final String category;
  final int displayOrder;
  final String? description;
  final List<String> recommendedBodyTypes;
  final List<String> specialHandling;
  final double? typicalWeightDensity; // kg per cubic meter
  final bool isPerishable;
  final bool isHazardous;
  final bool requiresSpecialPermit;

  const MaterialType({
    required this.id,
    required this.name,
    required this.category,
    required this.displayOrder,
    this.description,
    this.recommendedBodyTypes = const [],
    this.specialHandling = const [],
    this.typicalWeightDensity,
    this.isPerishable = false,
    this.isHazardous = false,
    this.requiresSpecialPermit = false,
  });

  MaterialType copyWith({
    int? id,
    String? name,
    String? category,
    int? displayOrder,
    String? description,
    List<String>? recommendedBodyTypes,
    List<String>? specialHandling,
    double? typicalWeightDensity,
    bool? isPerishable,
    bool? isHazardous,
    bool? requiresSpecialPermit,
  }) {
    return MaterialType(
      id: id ?? this.id,
      name: name ?? this.name,
      category: category ?? this.category,
      displayOrder: displayOrder ?? this.displayOrder,
      description: description ?? this.description,
      recommendedBodyTypes: recommendedBodyTypes ?? this.recommendedBodyTypes,
      specialHandling: specialHandling ?? this.specialHandling,
      typicalWeightDensity: typicalWeightDensity ?? this.typicalWeightDensity,
      isPerishable: isPerishable ?? this.isPerishable,
      isHazardous: isHazardous ?? this.isHazardous,
      requiresSpecialPermit: requiresSpecialPermit ?? this.requiresSpecialPermit,
    );
  }

  @override
  List<Object?> get props => [
        id,
        name,
        category,
        displayOrder,
        description,
        recommendedBodyTypes,
        specialHandling,
        typicalWeightDensity,
        isPerishable,
        isHazardous,
        requiresSpecialPermit,
      ];

  // Static factory methods for Indian material types
  static List<MaterialType> getIndianMaterialTypes() {
    return [
      // Agriculture (25 types)
      MaterialType(
        id: 1,
        name: 'Grains - Rice',
        category: 'Agriculture',
        displayOrder: 1,
        description: 'Rice, wheat, pulses, cereals',
        recommendedBodyTypes: ['Open Body', 'Container'],
        specialHandling: ['Moisture control', 'Pest control'],
        typicalWeightDensity: 750.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 2,
        name: 'Vegetables - Fresh',
        category: 'Agriculture',
        displayOrder: 2,
        description: 'Fresh vegetables, leafy greens',
        recommendedBodyTypes: ['Refrigerated', 'Open Body'],
        specialHandling: ['Temperature control', 'Ventilation'],
        typicalWeightDensity: 600.0,
        isPerishable: true,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 3,
        name: 'Fruits - Fresh',
        category: 'Agriculture',
        displayOrder: 3,
        description: 'Fresh fruits, seasonal produce',
        recommendedBodyTypes: ['Refrigerated', 'Container'],
        specialHandling: ['Temperature control', 'Gentle handling'],
        typicalWeightDensity: 650.0,
        isPerishable: true,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 4,
        name: 'Spices',
        category: 'Agriculture',
        displayOrder: 4,
        description: 'Turmeric, chili, coriander, cardamom',
        recommendedBodyTypes: ['Container', 'Open Body'],
        specialHandling: ['Moisture control', 'Airtight packaging'],
        typicalWeightDensity: 500.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 5,
        name: 'Dairy Products',
        category: 'Agriculture',
        displayOrder: 5,
        description: 'Milk, cheese, butter, ghee',
        recommendedBodyTypes: ['Refrigerated', 'Tanker'],
        specialHandling: ['Temperature control', 'Hygiene'],
        typicalWeightDensity: 1000.0,
        isPerishable: true,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 6,
        name: 'Poultry & Eggs',
        category: 'Agriculture',
        displayOrder: 6,
        description: 'Chicken, eggs, meat products',
        recommendedBodyTypes: ['Refrigerated', 'Specialized'],
        specialHandling: ['Temperature control', 'Ventilation'],
        typicalWeightDensity: 800.0,
        isPerishable: true,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),

      // Manufacturing (20 types)
      MaterialType(
        id: 7,
        name: 'Steel Products',
        category: 'Manufacturing',
        displayOrder: 7,
        description: 'Steel bars, sheets, structural steel',
        recommendedBodyTypes: ['Flatbed', 'Container'],
        specialHandling: ['Heavy lifting', 'Securing'],
        typicalWeightDensity: 7850.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 8,
        name: 'Cement & Concrete',
        category: 'Manufacturing',
        displayOrder: 8,
        description: 'Cement bags, concrete blocks',
        recommendedBodyTypes: ['Open Body', 'Container'],
        specialHandling: ['Moisture protection', 'Careful handling'],
        typicalWeightDensity: 1500.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 9,
        name: 'Machinery Parts',
        category: 'Manufacturing',
        displayOrder: 9,
        description: 'Industrial machinery, equipment parts',
        recommendedBodyTypes: ['Flatbed', 'Container', 'Specialized'],
        specialHandling: ['Shock protection', 'Securing'],
        typicalWeightDensity: 2000.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 10,
        name: 'Textiles',
        category: 'Manufacturing',
        displayOrder: 10,
        description: 'Fabric, garments, raw materials',
        recommendedBodyTypes: ['Container', 'Open Body'],
        specialHandling: ['Moisture protection', 'Folding'],
        typicalWeightDensity: 400.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 11,
        name: 'Chemicals',
        category: 'Manufacturing',
        displayOrder: 11,
        description: 'Industrial chemicals, solvents',
        recommendedBodyTypes: ['Tanker', 'Specialized'],
        specialHandling: ['Leak protection', 'Safety gear'],
        typicalWeightDensity: 1200.0,
        isPerishable: false,
        isHazardous: true,
        requiresSpecialPermit: true,
      ),

      // FMCG (15 types)
      MaterialType(
        id: 12,
        name: 'Packaged Foods',
        category: 'FMCG',
        displayOrder: 12,
        description: 'Processed foods, packaged goods',
        recommendedBodyTypes: ['Container', 'Open Body'],
        specialHandling: ['Sealed packaging', 'Stacking'],
        typicalWeightDensity: 600.0,
        isPerishable: true,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 13,
        name: 'Beverages',
        category: 'FMCG',
        displayOrder: 13,
        description: 'Soft drinks, juices, water',
        recommendedBodyTypes: ['Tanker', 'Container'],
        specialHandling: ['Temperature control', 'Sealing'],
        typicalWeightDensity: 1000.0,
        isPerishable: true,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 14,
        name: 'Personal Care',
        category: 'FMCG',
        displayOrder: 14,
        description: 'Cosmetics, toiletries, personal items',
        recommendedBodyTypes: ['Container', 'Open Body'],
        specialHandling: ['Fragile handling', 'Sealed packaging'],
        typicalWeightDensity: 800.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 15,
        name: 'Household Items',
        category: 'FMCG',
        displayOrder: 15,
        description: 'Home appliances, furniture',
        recommendedBodyTypes: ['Container', 'Flatbed'],
        specialHandling: ['Fragile handling', 'Padding'],
        typicalWeightDensity: 500.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),

      // Construction (15 types)
      MaterialType(
        id: 16,
        name: 'Building Materials',
        category: 'Construction',
        displayOrder: 16,
        description: 'Bricks, blocks, tiles, pipes',
        recommendedBodyTypes: ['Open Body', 'Flatbed'],
        specialHandling: ['Heavy lifting', 'Securing'],
        typicalWeightDensity: 2000.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 17,
        name: 'Sand & Aggregates',
        category: 'Construction',
        displayOrder: 17,
        description: 'River sand, construction sand, aggregates',
        recommendedBodyTypes: ['Open Body', 'Tipper'],
        specialHandling: ['Dust control', 'Moisture control'],
        typicalWeightDensity: 1600.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 18,
        name: 'Steel Bars',
        category: 'Construction',
        displayOrder: 18,
        description: 'Reinforcement steel, TMT bars',
        recommendedBodyTypes: ['Flatbed', 'Container'],
        specialHandling: ['Heavy lifting', 'Securing'],
        typicalWeightDensity: 7850.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 19,
        name: 'Pipes & Fittings',
        category: 'Construction',
        displayOrder: 19,
        description: 'PVC, GI, CPVC pipes',
        recommendedBodyTypes: ['Open Body', 'Container'],
        specialHandling: ['Length management', 'Stacking'],
        typicalWeightDensity: 1500.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),

      // Automotive (10 types)
      MaterialType(
        id: 20,
        name: 'Vehicles',
        category: 'Automotive',
        displayOrder: 20,
        description: 'Cars, motorcycles, auto parts',
        recommendedBodyTypes: ['Flatbed', 'Specialized'],
        specialHandling: ['Careful handling', 'Securing'],
        typicalWeightDensity: 500.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 21,
        name: 'Auto Parts',
        category: 'Automotive',
        displayOrder: 21,
        description: 'Engine parts, batteries, tyres',
        recommendedBodyTypes: ['Container', 'Open Body'],
        specialHandling: ['Oil protection', 'Securing'],
        typicalWeightDensity: 1500.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 22,
        name: 'Tyres',
        category: 'Automotive',
        displayOrder: 22,
        description: 'New and used tyres',
        recommendedBodyTypes: ['Open Body', 'Flatbed'],
        specialHandling: ['Stacking', 'Load distribution'],
        typicalWeightDensity: 1200.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 23,
        name: 'Lubricants',
        category: 'Automotive',
        displayOrder: 23,
        description: 'Engine oil, transmission oil, grease',
        recommendedBodyTypes: ['Tanker', 'Container'],
        specialHandling: ['Leak protection', 'Sealing'],
        typicalWeightDensity: 900.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),

      // Electronics (8 types)
      MaterialType(
        id: 24,
        name: 'Appliances',
        category: 'Electronics',
        displayOrder: 24,
        description: 'Home appliances, electronics',
        recommendedBodyTypes: ['Container', 'Open Body'],
        specialHandling: ['Fragile handling', 'Padding'],
        typicalWeightDensity: 400.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 25,
        name: 'Computers & IT Equipment',
        category: 'Electronics',
        displayOrder: 25,
        description: 'Desktops, laptops, servers',
        recommendedBodyTypes: ['Container', 'Specialized'],
        specialHandling: ['Shock protection', 'Anti-static'],
        typicalWeightDensity: 300.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 26,
        name: 'Mobile Phones',
        category: 'Electronics',
        displayOrder: 26,
        description: 'Smartphones, tablets, accessories',
        recommendedBodyTypes: ['Container', 'Open Body'],
        specialHandling: ['Fragile handling', 'Padding'],
        typicalWeightDensity: 200.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),

      // Pharmaceuticals (7 types)
      MaterialType(
        id: 27,
        name: 'Medicines',
        category: 'Pharmaceuticals',
        displayOrder: 27,
        description: 'Tablets, capsules, injections',
        recommendedBodyTypes: ['Refrigerated', 'Container'],
        specialHandling: ['Temperature control', 'Security'],
        typicalWeightDensity: 800.0,
        isPerishable: true,
        isHazardous: false,
        requiresSpecialPermit: true,
      ),
      MaterialType(
        id: 28,
        name: 'Medical Equipment',
        category: 'Pharmaceuticals',
        displayOrder: 28,
        description: 'Medical devices, equipment',
        recommendedBodyTypes: ['Container', 'Specialized'],
        specialHandling: ['Careful handling', 'Calibration'],
        typicalWeightDensity: 1000.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 29,
        name: 'Pharmaceutical Chemicals',
        category: 'Pharmaceuticals',
        displayOrder: 29,
        description: 'Raw materials, chemicals',
        recommendedBodyTypes: ['Tanker', 'Specialized'],
        specialHandling: ['Safety gear', 'Leak protection'],
        typicalWeightDensity: 1200.0,
        isPerishable: false,
        isHazardous: true,
        requiresSpecialPermit: true,
      ),

      // Textiles (8 types)
      MaterialType(
        id: 30,
        name: 'Fabrics',
        category: 'Textiles',
        displayOrder: 30,
        description: 'Cotton, silk, synthetic fabrics',
        recommendedBodyTypes: ['Container', 'Open Body'],
        specialHandling: ['Moisture protection', 'Folding'],
        typicalWeightDensity: 400.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 31,
        name: 'Garments',
        category: 'Textiles',
        displayOrder: 31,
        description: 'Ready-made garments, clothing',
        recommendedBodyTypes: ['Container', 'Open Body'],
        specialHandling: ['Hanging storage', 'Folding'],
        typicalWeightDensity: 200.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 32,
        name: 'Raw Materials',
        category: 'Textiles',
        displayOrder: 32,
        description: 'Cotton, jute, synthetic fibers',
        recommendedBodyTypes: ['Open Body', 'Container'],
        specialHandling: ['Moisture protection', 'Bale handling'],
        typicalWeightDensity: 600.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),

      // Petroleum (8 types)
      MaterialType(
        id: 33,
        name: 'Fuel',
        category: 'Petroleum',
        displayOrder: 33,
        description: 'Petrol, diesel, aviation fuel',
        recommendedBodyTypes: ['Tanker', 'Specialized'],
        specialHandling: ['Leak protection', 'Safety gear'],
        typicalWeightDensity: 750.0,
        isPerishable: false,
        isHazardous: true,
        requiresSpecialPermit: true,
      ),
      MaterialType(
        id: 34,
        name: 'Lubricants & Greases',
        category: 'Petroleum',
        displayOrder: 34,
        description: 'Engine oil, hydraulic oil, greases',
        recommendedBodyTypes: ['Tanker', 'Container'],
        specialHandling: ['Leak protection', 'Sealing'],
        typicalWeightDensity: 900.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 35,
        name: 'Gas Cylinders',
        category: 'Petroleum',
        displayOrder: 35,
        description: 'LPG, CNG, industrial gases',
        recommendedBodyTypes: ['Specialized'],
        specialHandling: ['Safety gear', 'Upright storage'],
        typicalWeightDensity: 600.0,
        isPerishable: false,
        isHazardous: true,
        requiresSpecialPermit: true,
      ),

      // Others (10 types)
      MaterialType(
        id: 36,
        name: 'Furniture',
        category: 'Others',
        displayOrder: 36,
        description: 'Wooden furniture, office furniture',
        recommendedBodyTypes: ['Container', 'Flatbed'],
        specialHandling: ['Padding', 'Protection'],
        typicalWeightDensity: 300.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 37,
        name: 'Glass Products',
        category: 'Others',
        displayOrder: 37,
        description: 'Glass sheets, mirrors, bottles',
        recommendedBodyTypes: ['Specialized', 'Container'],
        specialHandling: ['Fragile handling', 'Securing'],
        typicalWeightDensity: 2500.0,
        isPerishable: false,
        isHazardous: true,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 38,
        name: 'Paper Products',
        category: 'Others',
        displayOrder: 38,
        description: 'Paper, cardboard, packaging',
        recommendedBodyTypes: ['Container', 'Open Body'],
        specialHandling: ['Moisture protection', 'Stacking'],
        typicalWeightDensity: 700.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 39,
        name: 'Plastics',
        category: 'Others',
        displayOrder: 39,
        description: 'Raw materials, finished products',
        recommendedBodyTypes: ['Container', 'Open Body'],
        specialHandling: ['Heat protection', 'Sorting'],
        typicalWeightDensity: 900.0,
        isPerishable: false,
        isHazardous: false,
        requiresSpecialPermit: false,
      ),
      MaterialType(
        id: 40,
        name: 'Waste Materials',
        category: 'Others',
        displayOrder: 40,
        description: 'Recyclable waste, scrap materials',
        recommendedBodyTypes: ['Open Body', 'Container'],
        specialHandling: ['Segregation', 'Safety gear'],
        typicalWeightDensity: 500.0,
        isPerishable: false,
        isHazardous: true,
        requiresSpecialPermit: false,
      ),
    ];
  }

  // Category-wise grouping
  static List<String> getCategories() {
    return [
      'Agriculture',
      'Manufacturing',
      'FMCG',
      'Construction',
      'Automotive',
      'Electronics',
      'Pharmaceuticals',
      'Textiles',
      'Petroleum',
      'Others',
    ];
  }

  // Get materials by category
  static List<MaterialType> getMaterialsByCategory(String category) {
    return getIndianMaterialTypes()
        .where((material) => material.category == category)
        .toList();
  }

  // Smart material-to-body type mapping
  static Map<String, List<String>> getMaterialBodyMapping() {
    return {
      'Grains': ['Open Body', 'Container'],
      'Vegetables': ['Refrigerated', 'Container'],
      'Fruits': ['Refrigerated', 'Container'],
      'Spices': ['Container', 'Open Body'],
      'Dairy': ['Refrigerated', 'Tanker'],
      'Poultry': ['Refrigerated', 'Specialized'],
      'Steel': ['Flatbed', 'Container'],
      'Cement': ['Open Body', 'Container'],
      'Machinery': ['Flatbed', 'Container', 'Specialized'],
      'Textiles': ['Container', 'Open Body'],
      'Chemicals': ['Tanker', 'Specialized'],
      'Liquids': ['Tanker', 'Specialized'],
      'Heavy Machinery': ['Flatbed', 'Trailer'],
      'Fragile Goods': ['Container', 'Refrigerated'],
      'Perishable': ['Refrigerated', 'Container'],
      'Oversized': ['Flatbed', 'Trailer'],
    };
  }

  // Get materials by body type compatibility
  static List<MaterialType> getMaterialsForBodyType(String bodyType) {
    final mapping = getMaterialBodyMapping();
    final compatibleMaterials = <String>[];
    
    mapping.forEach((material, bodyTypes) {
      if (bodyTypes.contains(bodyType)) {
        compatibleMaterials.add(material);
      }
    });
    
    return getIndianMaterialTypes()
        .where((material) => compatibleMaterials.contains(material.name))
        .toList();
  }
}
